### ISSUE TITLE
All tools need to render like they are actual tools and not items

### ISSUE THREAD

**Issue by DrasticDemise** [baileyholl/Aura-Cascade#19]

**Comment by williewillus** [comment]
_All_ usages of "standard_item" like here
https://github.com/DrasticDemise/Aura-Cascade/blob/MC188/src/main/resources/assets/aura/models/item/storageBook.json#L2
Need to be replaced with "minecraft:item/generated"

_All_ usages of "standard_tool" need to be replaced with "miencraft:item/handheld"

After that is done, standard_item/tool can be deleted

**Comment by williewillus** [comment]
Doing that will close this one and #18
